In [28]:
40*4*4

640

In [8]:
import numpy as np
indices=np.random.randint(10, size=10)
#indices = np.random.randint(n_categorical, size=n)
one_hot = np.zeros((10, 10))
one_hot[np.arange(10), indices] = 1

In [13]:
c_categorical=one_hot
categories =indices

In [9]:
print one_hot
print indices

[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]]
[0 7 5 5 4 9 5 0 2 9]


In [19]:
c_continuous=np.random.normal(0, 1, size=(10, 2))
c_continuous.shape

(10L, 2L)

In [12]:
zs = np.random.uniform(-1, 1, (10, 2)).astype(np.float32)
zs

array([[ 0.38883212, -0.3579464 ],
       [ 0.48332351,  0.62903064],
       [-0.03473154, -0.97652167],
       [ 0.13537098, -0.55361301],
       [-0.5939405 ,  0.51947188],
       [ 0.5369097 ,  0.74051398],
       [ 0.12680064,  0.86597639],
       [ 0.90782166, -0.88140237],
       [ 0.11709381,  0.12698877],
       [ 0.54199648, -0.82190877]], dtype=float32)

In [20]:
np.concatenate((zs, c_categorical, c_continuous), axis=1)

array([[ 0.38883212, -0.3579464 ,  1.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        , -1.48748283, -0.99295811],
       [ 0.48332351,  0.62903064,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  2.1993238 , -0.02538373],
       [-0.03473154, -0.97652167,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.63246588,  0.89625535],
       [ 0.13537098, -0.55361301,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         0.        ,  0.        , -0.98384896, -0.45354731],
       [-0.5939405 ,  0.51947188,  0.        ,  0.        ,  0.        ,
         0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.  

In [ ]:
from chainer import functions as F
F.split_axis(mi, [n_categorical], 1)
